import { useEffect, useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import {
  TrendingUp,
  TrendingDown,
  Wallet,
  AlertTriangle,
  Sparkles,
  Mic,
  Landmark,
  RefreshCw,
  Loader2,
} from 'lucide-react';
import AppShell from '../components/layout/AppShell.jsx';
import HealthScoreGauge from '../components/ui/HealthScoreGauge.jsx';
import CashflowChart from '../components/ui/CashflowChart.jsx';
import StatCard from '../components/ui/StatCard.jsx';
import TransactionItem from '../components/ui/TransactionItem.jsx';
import EmptyState from '../components/ui/EmptyState.jsx';
import Loader from '../components/ui/Loader.jsx';
import { dashboardApi, insightsApi } from '../lib/api';
import { formatTaka, categoryLabel } from '../lib/format';
import useAuth from '../context/useAuth.js';
import useToast from '../context/useToast.js';

export default function Dashboard() {
  const { user } = useAuth();
  const toast = useToast();
  const [overview, setOverview] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const loadOverview = useCallback(async () => {
    try {
      const data = await dashboardApi.getOverview();
      setOverview(data);
    } catch (err) {
      toast.error(err.message);
    } finally {
      setLoading(false);
    }
  }, [toast]);

  useEffect(() => {
    loadOverview();
  }, [loadOverview]);

  const handleGenerateSummary = async () => {
    setGenerating(true);
    try {
      await insightsApi.generateSummary('weekly');
      toast.success('Weekly summary generated by Gemma 4');
      await loadOverview();
    } catch (err) {
      toast.error(err.message);
    } finally {
      setGenerating(false);
    }
  };

  if (loading) {
    return (
      <AppShell title="Dashboard">
        <Loader label="Loading your dashboard…" />
      </AppShell>
    );
  }

  const snapshot = overview?.snapshot;
  const hasData = overview?.recentTransactions?.length > 0;

  return (
    <AppShell title="Dashboard">
      {/* Mobile greeting (desktop title shown by AppShell) */}
      <div className="lg:hidden mb-4">
        <h2 className="font-display text-xl font-bold text-neutral">
          Hi, {user?.name?.split(' ')[0] || 'there'} 👋
        </h2>
      </div>

      {!hasData && (
        <EmptyState
          icon={Mic}
          title="No transactions logged yet"
          description="Start by logging your first sale or expense — by voice or a quick form."
          action={
            <Link to="/log-entry" className="btn-brand btn btn-sm gap-2 mt-2">
              <Mic size={15} /> Log your first entry
            </Link>
          }
        />
      )}

      {hasData && (
        <>
          {snapshot?.warningFlag && (
            <div className="alert bg-error/10 border border-error/20 text-error rounded-2xl mb-6 items-start">
              <AlertTriangle size={18} className="mt-0.5 shrink-0" />
              <div>
                <p className="font-semibold text-sm">Cash-flow warning</p>
                <p className="font-bn text-sm mt-0.5 opacity-90">{snapshot.warningMessage}</p>
              </div>
            </div>
          )}

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
            {/* Health score */}
            <div className="card-surface p-6 flex flex-col items-center justify-center">
              <p className="text-xs font-medium text-base-content/50 uppercase tracking-wide mb-3 self-start">
                Financial Health Score
              </p>
              <HealthScoreGauge score={snapshot?.healthScore || 0} />
              {snapshot?.healthScoreExplanation && (
                <p className="font-bn text-xs text-base-content/60 text-center mt-4 leading-relaxed">
                  {snapshot.healthScoreExplanation}
                </p>
              )}
            </div>

            {/* Stats + chart */}
            <div className="lg:col-span-2 space-y-6">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <StatCard
                  icon={TrendingUp}
                  label="Income"
                  value={formatTaka(snapshot?.totalIncome || 0)}
                  tone="success"
                />
                <StatCard
                  icon={TrendingDown}
                  label="Expense"
                  value={formatTaka(snapshot?.totalExpense || 0)}
                  tone="error"
                />
                <StatCard
                  icon={Wallet}
                  label="Net Profit"
                  value={formatTaka(snapshot?.netProfit || 0)}
                  tone="gold"
                />
              </div>

              <div className="card-surface p-5">
                <div className="flex items-center justify-between mb-2">
                  <p className="font-display font-semibold text-neutral text-sm">
                    7-Day Cash-Flow Forecast
                  </p>
                </div>
                <CashflowChart forecast={snapshot?.cashflowForecast || []} />
              </div>
            </div>
          </div>

          {/* AI summary CTA */}
          <div className="card-surface p-5 mb-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 bg-taka-gradient">
            <div className="flex items-start gap-3">
              <div className="rounded-lg bg-white/15 p-2 text-white shrink-0">
                <Sparkles size={18} />
              </div>
              <div>
                <p className="font-display font-semibold text-white text-sm">
                  Refresh your Gemma 4 financial summary
                </p>
                <p className="text-white/70 text-xs mt-0.5">
                  Recomputes your health score, forecast, and plain-Bangla explanation from the latest data.
                </p>
              </div>
            </div>
            <button
              onClick={handleGenerateSummary}
              disabled={generating}
              className="btn btn-sm bg-white text-neutral hover:bg-white/90 border-none gap-2 shrink-0"
            >
              {generating ? <Loader2 size={14} className="animate-spin" /> : <RefreshCw size={14} />}
              Generate summary
            </button>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Recent transactions */}
            <div className="lg:col-span-2 card-surface p-2">
              <div className="flex items-center justify-between px-4 py-3">
                <p className="font-display font-semibold text-neutral text-sm">Recent Activity</p>
                <Link to="/history" className="text-xs text-primary font-medium hover:underline">
                  View all
                </Link>
              </div>
              <div className="divide-y divide-base-300/50">
                {overview.recentTransactions.map((t) => (
                  <TransactionItem key={t._id} transaction={t} />
                ))}
              </div>
            </div>

            {/* Category breakdown + loan CTA */}
            <div className="space-y-6">
              <div className="card-surface p-5">
                <p className="font-display font-semibold text-neutral text-sm mb-3">Top Expense Categories</p>
                <div className="space-y-3">
                  {overview.categoryBreakdown.slice(0, 5).map((c) => (
                    <div key={c.category} className="flex items-center justify-between text-sm">
                      <span className="text-base-content/70">{categoryLabel(c.category)}</span>
                      <span className="font-medium text-neutral">{formatTaka(c.amount)}</span>
                    </div>
                  ))}
                  {overview.categoryBreakdown.length === 0 && (
                    <p className="text-xs text-base-content/40">No expenses logged yet.</p>
                  )}
                </div>
              </div>

              <Link
                to="/loans"
                className="card-surface p-5 flex items-center gap-3 hover:shadow-lg transition group"
              >
                <div className="rounded-xl bg-secondary/10 text-secondary p-2.5">
                  <Landmark size={20} />
                </div>
                <div className="flex-1">
                  <p className="font-display font-semibold text-neutral text-sm">
                    Check loan eligibility
                  </p>
                  <p className="text-xs text-base-content/50">See which lenders you qualify for</p>
                </div>
              </Link>
            </div>
          </div>
        </>
      )}
    </AppShell>
  );
}
